name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 8 * * *'
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "8"
          remove_duplicates: true
          feed_list: "https://www.writeup-db.com/feed/"
          readme_path: "profile/README.md"
